Final PR! Added sheet protection for Sheet and a decorator to handle that.
chrispcharlton/automate_excel pull request #32
Opened 2021-10-30 00:12 UTC by jTaylo99

Added protected property to Sheet and created a decorator for functions of Sheet to run without protection on.
 @chrispcharlton Decorators were actually pretty interesting to work with, I can for sure see how they'd be useful to become proficient with.

2021-10-30 04:41 UTC, chrispcharlton requested changes

2021-10-30 04:41 UTC, chrispcharlton commented on src/sheet.py
> +        self.sheet = None
You should be able to remove this as the `if else` block below will always assign `self.sheet`.

2021-10-31 01:10 UTC, chrispcharlton commented
You'll need to fix up merge conflicts unfortunately

2021-10-31 02:01 UTC, jTaylo99 commented
Resolved! There was a function I must have accidentally removed.

2021-10-31 02:53 UTC, merged